#!/bin/sh -ex
trap 'rm -rf "$tmp"' INT TERM EXIT HUP
tmp=$(git-hooks-workdir "$@")

cd "$tmp/doc"
notwiki-doc html /srv/http/vhost/code/passlock *
notwiki-doc gph  /srv/gopher/passlock *
notwiki-mandoc html html /srv/http/vhost/code/man *
notwiki-mandoc html html /srv/gopher/man *

cd "$tmp"
make dist
cp *.tar.gz /srv/http/vhost/code/notwiki
cp *.tar.gz /srv/gopher/notwiki
