.Dt PASSLIST 1
.Dd $Mdocdate: August 14 2019$
.Os
.
.
.Sh NAME
.
.Nm passlist-check
.Nd check an username against a passlist file
.
.
.Sh SYNOPSIS
.
.Nm passlist-check
.Op Fl v
.Op Fl f Ar passfile
.Ar ...
.Ar 3<user-pass
.
.
.Sh DESCRIPTION
.
The
.Nm
utility read a checkpassword-formatted string from file descriptor 3, and checks
it against the passlist file used.
.
.Pp
The checkpasswd format used is:
.
.Dl user\\\\0password\\\\0realm
.
.Pp
The realm information is ignored.
.
.Bl -tag -width 6n
.
.It Fl v
Display the version.
.
.It Fl f Ar passfile
Specifies the file to use as a password storage.
.
.El
.
.
.Sh FILES
.
The default passfile is
.Pa /etc/passlist/default .
.
.
.Sh EXIT STATUS
.
.Ex -std
.
.
.Sh EXAMPLES
.
.Bd -literal
$ authd passlist-check -f /etc/passlist/servicename protected-daemon -args
.Ed
.
.
.Sh SEE ALSO
.
.Xr passlist-add 1
.Xr passlist-del 1
.Xr passlist-list 1
.
.
.Sh STANDARDS
.
.Lk "checkpassword: a simple password-checking interface" https://cr.yp.to/checkpwd.html
.
.
.Sh AUTHORS
.
.An Josuah Demangeon
.Aq Mt man@josuah.net
.
.
.Sh CAVEATS
.
The argon2di hash function used is very secure at the cost of being
resource-expensive, which might represent a rather large amount of time
according to the hardware.
