.Dt PASSLIST 1
.Dd $Mdocdate: August 14 2019$
.Os
.
.
.Sh NAME
.
.Nm passlist-add
.Nm passlist-del
.Nm passlist-list
.Nd manage text-based password files
.
.
.Sh SYNOPSIS
.
.Nm passlist-add
.Op Fl v
.Op Fl f Ar passfile
.Ar user
.Ar path
.Ar <passphrase
.
.Nm passlist-del
.Op Fl v
.Op Fl f Ar passfile
.Ar user
.
.
.Nm passlist-list
.Op Fl v
.Op Fl f Ar passfile
.
.
.Sh DESCRIPTION
.
The
.Nm passlist-add
utility add a passphrase to the passfile with the
.Ar user
and
.Ar path
specified by the arguments.
It reads a single line from stdin used as a passphrase.
.
.Pp
The
.Nm passlist-del
utility delete the
.Ar user
passed as argument from the passfile.
.
.Pp
The
.Nm passlist-list
utility list users contained in the passfile.
.
These flags are common to all passlist commands:
.
.Bl -tag -width 6n
.
.It Fl v
Display the version.
.
.It Fl f Ar passfile
Specifies the file to use as a password storage.
.
.El
.
.
.Sh FILES
.
The default passfile is
.Pa /etc/passlist/default .
.
.
.Sh EXIT STATUS
.
.Ex -std
.
.
.Sh EXAMPLES
.
.
.
.Sh SEE ALSO
.
.Xr passlist-check 1
.
.Sh HISTORY
.
The passlist utilities have originally been written for the
.Xr tinimap 8
imap server.
.
.
.Sh AUTHORS
.
.An <author-name>
.Aq Mt <author-email>
.
.
.Sh CAVEATS
.
.
.
.Sh BUGS
.
